const http=require('node:http'),{spawn}=require('node:child_process'),path=require('node:path'),fs=require('node:fs');
const PORT=Number(process.env.PORT||8787),ROOT=__dirname,MAX_BODY=16*1024,MAX_JOBS=2;let jobs=0;
function videoId(value){try{const u=new URL(String(value).trim());let id=u.hostname.includes('youtu.be')?u.pathname.slice(1).split('/')[0]:u.hostname.includes('youtube.com')?(u.searchParams.get('v')||u.pathname.match(/(?:shorts|embed|live)\/([^/?]+)/)?.[1]):null;return id&&/^[A-Za-z0-9_-]{6,}$/.test(id)?id:null}catch{return null}}
function reply(res,status,body){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(body))}
function runAnalysis(id){return new Promise((resolve,reject)=>{const args=['--no-playlist','--no-warnings','--force-ipv4','--socket-timeout','20','--retries','2','--fragment-retries','2','--js-runtimes','deno','--extractor-args','youtube:player_client=web','-f','bestaudio/best','-o','-',`https://www.youtube.com/watch?v=${id}`];const dl=spawn('yt-dlp',args,{stdio:['ignore','pipe','pipe']}),ff=spawn('ffmpeg',['-hide_banner','-loglevel','error','-i','pipe:0','-t','60','-vn','-ac','1','-ar','22050','-f','f32le','pipe:1'],{stdio:['pipe','pipe','pipe']});let chunks=[],total=0,errors='',done=false;const finish=(err,value)=>{if(done)return;done=true;clearTimeout(timer);dl.kill('SIGKILL');ff.kill('SIGKILL');err?reject(err):resolve(value)};const timer=setTimeout(()=>finish(Error('Audio extraction timed out')),120000);dl.stdout.pipe(ff.stdin);ff.stdin.on('error',()=>{});ff.stdout.on('data',c=>{if(total<8*1024*1024){chunks.push(c);total+=c.length}});dl.stderr.on('data',c=>errors+=c);ff.stderr.on('data',c=>errors+=c);dl.on('error',finish);ff.on('error',finish);ff.on('close',code=>{if(code!==0||!chunks.length)return finish(Error(errors.toString().trim()||'Could not decode audio'));finish(null,analyze(Buffer.concat(chunks),22050))});dl.on('close',code=>{if(code!==0)ff.stdin.destroy()})})}
function analyze(buffer,rate){const data=new Float32Array(Math.floor(buffer.length/4));for(let i=0;i<data.length;i++)data[i]=buffer.readFloatLE(i*4);const detected=key(data,rate);return{bpm:bpm(data,rate),key:detected.key,mode:detected.mode,seconds:Math.min(60,Math.floor(data.length/rate))}}
function bpm(data,rate){const hop=Math.floor(rate/100),env=[];let prev=0;for(let i=0;i+hop<data.length;i+=hop){let e=0;for(let j=0;j<hop;j+=8)e+=Math.abs(data[i+j]||0);env.push(Math.max(0,e-prev*.92));prev=e}let best=34,score=-1;for(let lag=34;lag<=100;lag++){let s=0;for(let i=lag;i<env.length;i++)s+=env[i]*env[i-lag];if(s>score){score=s;best=lag}}let value=Math.round(6000/best);while(value<70)value*=2;while(value>160)value/=2;return Math.round(value)}
function key(data,rate){const size=4096,chrom=new Array(12).fill(0),step=Math.floor(rate*.45);for(let start=0,frame=0;start+size<data.length&&frame<90;start+=step,frame++)for(let bin=3;bin<size/2;bin++){const f=bin*rate/size;if(f<65||f>2100)continue;let re=0,im=0;for(let n=0;n<size;n+=8){const a=2*Math.PI*bin*n/size,s=data[start+n]||0;re+=s*Math.cos(a);im-=s*Math.sin(a)}const midi=Math.round(69+12*Math.log2(f/440));chrom[(midi%12+12)%12]+=re*re+im*im}const names=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'],maj=[6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88],min=[6.33,2.68,3.52,5.38,2.6,3.53,2.54,4.75,3.98,2.69,3.34,3.17];let best={score:-Infinity,key:'C',mode:'major'};for(let root=0;root<12;root++)for(const[mode,p]of[['major',maj],['minor',min]]){let s=0;for(let i=0;i<12;i++)s+=chrom[(i+root)%12]*p[i];if(s>best.score)best={score:s,key:names[root],mode}}return best}
function staticFile(req,res){const pathname=new URL(req.url,`http://${req.headers.host}`).pathname,file=path.normalize(path.join(ROOT,pathname==='/'?'/index.html':pathname));if((file!==ROOT&&!file.startsWith(ROOT+path.sep))||!fs.existsSync(file)||fs.statSync(file).isDirectory())return reply(res,404,{error:'Not found'});const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};res.writeHead(200,{'content-type':types[path.extname(file)]||'application/octet-stream'});if(req.method==='HEAD')return res.end();fs.createReadStream(file).pipe(res)}
http.createServer((req,res)=>{if(req.method==='POST'&&req.url==='/api/analyze'){let body='',large=false;req.on('data',c=>{body+=c;if(body.length>MAX_BODY)large=true});req.on('end',async()=>{if(large)return reply(res,413,{error:'Request is too large.'});let payload;try{payload=JSON.parse(body)}catch{return reply(res,400,{error:'Invalid request.'})}const id=videoId(payload.url);if(!id)return reply(res,400,{error:'Please provide a valid YouTube URL.'});if(jobs>=MAX_JOBS)return reply(res,429,{error:'The analyzer is busy. Please try again in a moment.'});jobs++;try{return reply(res,200,await runAnalysis(id))}catch(error){console.error(`[analyze:${id}]`,error.message);return reply(res,502,{error:'Could not read that video’s audio. Check that it is public and playable, then try again.'})}finally{jobs--}});return}if(req.method==='GET'||req.method==='HEAD')return staticFile(req,res);reply(res,405,{error:'Method not allowed'})}).listen(PORT,()=>console.log(`ytkey running at http://localhost:${PORT}`));
